sudo: false

language: java

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master

install:
  - mvn clean install -Dmaven.test.skip.exec

script:
  - mvn test
# To reactive with WildFly CDI 2.0 patching
#  - mvn test -Pwildfly -pl camel/further
#  - mvn test -Pwildfly -pl camel/bonus
#  - mvn test -Pwildfly -pl metrics/further

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - antonin.stefanutti@gmail.com
